--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ohYanoox/DialogueUIAPI
build-by-default: true
branches:
- main
projects:
  DialogueUIAPI:
    path: ""
    model: virion
    type: library
...
